### ISSUE TITLE
logo on login box erased after applying terraform

### ISSUE THREAD

**Issue by afterthought** [frontegg/terraform-provider-frontegg#10]
When we apply our terraform workspace the logo for the login box is removed.

### Terraform version

1.1.3

### Affected resources

frontegg_workspace

### Terraform configuration files

    provider "frontegg" {
      api_base_url    = "https://api.us.frontegg.com"
      portal_base_url = "https://portal.us.frontegg.com"
    }

    resource "frontegg_workspace" "saas_controller" {
      depends_on = [
        azurerm_dns_cname_record.frontegg
      ]
      name                = var.name
      country             = "US"
      frontend_stack      = "React"
      backend_stack       = "Python"
      open_saas_installed = false
    
      custom_domain   = "${azurerm_dns_cname_record.frontegg.name}.${var.dns_zone_name}"
      frontegg_domain = "${var.slug}.us.frontegg.com"
      allowed_origins = var.allowed_origins
    
      auth_policy {
        allow_unverified_users       = false
        allow_signups                = false
        enable_api_tokens            = true
        enable_roles                 = true
        jwt_algorithm                = "RS256"
        jwt_access_token_expiration  = 86400   # 1 day
        jwt_refresh_token_expiration = 2592000 # 30 days
        same_site_cookie_policy      = var.frontegg_cookie_policy
      }
    
    
    
      lockout_policy {
        max_attempts = 10
      }
    
      password_policy {
        allow_passphrases = false
        min_length        = 10
        max_length        = 128
        min_tests         = 2
        min_phrase_length = 6
        history           = 2
      }
    
    
      hosted_login {
        allowed_redirect_urls = var.allowed_redirect_urls
      }
    
      # saml {
      #   acs_url      = "https://mycompany.com/saml"
      #   sp_entity_id = "my-company"
      # }
    
      mfa_policy {
        allow_remember_device = true
        device_expiration     = 604800 # 7 days
        enforce               = "off"
      }
      user_activation_email {
        from_address  = var.from_address
        from_name     = var.name
        subject       = "Activate Your Account"
        html_template = templatefile("${path.module}/email-templates/user-activation.html", { name = var.name })
        redirect_url  = "https://domain/account/activate"
      }
    
      user_invitation_email {
        from_address  = var.from_address
        from_name     = var.name
        subject       = "${var.name} Invitation"
        html_template = templatefile("${path.module}/email-templates/user-invitation.html", { name = var.name })
        redirect_url  = "https://domain/account/invitation/accept"
      }
      admin_portal {
        enable_account_settings    = true
        enable_api_tokens          = true
        enable_audit_logs          = true
        enable_personal_api_tokens = false
        enable_privacy             = true
        enable_profile             = true
        enable_roles               = true
        enable_security            = true
        enable_sso                 = true
        enable_subscriptions       = true
        enable_usage               = true
        enable_users               = true
        enable_webhooks            = true
    
        palette {
          success        = "#2ca744"
          info           = "#5587c0"
          warning        = "#ffc107"
          error          = "#e1583e"
          primary        = "#43bb7a"
          primary_text   = "#ffffff"
          secondary      = "#fbfbfc"
          secondary_text = "#3c4a5a"
        }
      }
    
    }
### Debug Output

Secret Gist sent via DM.

### Panic output

No

### Expected Behavior

TBD. Open to a fix that just leaves the logo uploaded in the GUI or a fix that lets us supply the Logo to terraform.

### Actual Behavior

After running terraform, the logo created in the portal is removed.

### Steps to reproduce

1. Add logo to workspace
2. Run `terraform apply` 

### Important factoids

None

**Comment by aviadmizrachi** [comment]
Fixed on release v0.2.34
Thanks for your support!
