### ISSUE TITLE
Feature Request: Add ability to manage all emails via terraform provider

### ISSUE THREAD

**Issue by kris-swann** [frontegg/terraform-provider-frontegg#14]
Feature request: add support for all emails

Currently we have to manage some emails via terraform and the others manually, would be very nice to get all of these into terraform.

Currently the only emails that are supported for management via terraform are:
*  pwned_password_email
*  reset_password_email
*  user_activation_email 
*  user_invitation_email

This Issue is requesting the addition of all the emails on this screen:

Specifically:
* `Magic Link`
* `OTC`
* `Connect New Device`
* `User Used Invitation`

![image](https://user-images.githubusercontent.com/12589014/165638540-72960b1d-f4d3-4e12-9496-9110af55624e.png)

**Comment by aviadmizrachi** [comment]
Fixed on release v0.2.34
Thanks for your support!
