### ISSUE TITLE
Tenant resource has mandatory undocumented application_uri parameter

### ISSUE THREAD

**Issue by antifuchs** [frontegg/terraform-provider-frontegg#24]
### Terraform version

(all)

### Affected resources

* frontegg_tenant

### Terraform configuration files

(n/a)

### Expected Behavior

The frontegg_tenant resoure should not require a `application_uri` parameter to be passed; it's not documented on https://docs.frontegg.com/reference/tenantcontrollerv1_addtenant and according to frontegg folks, only serves to disambiguate oauth applications if there should be multiple on the domain.

### Actual Behavior

The parameter is mandatory: https://registry.terraform.io/providers/frontegg/frontegg/latest/docs/resources/tenant

### Steps to reproduce

Create a `frontegg_tenant` resource without the parameter (:

**Comment by aviadmizrachi** [comment]
Fixed on v0.2.22. Thanks for the contribution!
