### ISSUE TITLE
Support rest of email templates in the provider

### ISSUE THREAD

**Issue by kris-swann** [frontegg/terraform-provider-frontegg#43]
We have see the emojis in our unmanaged templates get cohersed into a `?` character which makes our emails look bad.

Currently the following email templates are not supported by the terraform provider, would be good to add those in so we no longer have to babysit our unmanaged email templates:

* Magic Link
* Connect New Device
* Magic Code
* User Used Invitation

**Comment by aviadmizrachi** [comment]
Fixed on release v0.2.34
Thanks for your support!
